os: linux
sudo: false
language: node_js
node_js:
  - '6'
before_script:
  - npm install -g gulp-cli
script: gulp
cache:
  directories:
    - node_modules
after_success:
  # test deployment for web (success)